version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      VERSION: '3.0.0'
      MAINTAINER: 'PBRP Team'
      VENDOR: 'realme'
      CODENAME: 'RMX1911'
      FLAVOR: 'eng'
      PB_OFFICIAL: 'true'
      CHANGELOG: |
        - Bringup 3.0 
        - Source side changes 
        - Fully Redesigned UI 
        - New Android like Power Menu (Activated via power key hold) 
        - Fixed Flashlight
        - Force use busybox
        - Disable DM-Verity by default
        - Renamed External-Device to USB-Storage
        - Etc.
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'android-9.0'
          context: org-global
